def gitUrl = 'https://github.com/spring-projects/spring-framework.git'
job {
    name 'exec-build'
    scm {
        git(gitUrl,'master'){
            configure { node ->
                'hudson.plugins.git.extensions.impl.UserIdentity'(){
                    name('jobolizer.ci')
                    email('jobolizer.ci@epam.com')
                }
            }
        }
    }
    triggers {
      scm('H/5 * * * *')
    }
    steps {
	gradle('build')
    }
}
